:r metadata/ValuePool/GEOAREAS.sql
:r metadata/ValuePool/SEX.sql
:r metadata/ValuePool/AGE.sql
:r metadata/ValuePool/CITIZENSHIP.sql
:r metadata/ValuePool/WASTE_CAT.sql
:r metadata/ValuePool/TREATMENT_CAT.sql
:r metadata/ValuePool/EMISSION.sql
:r metadata/ValuePool/GREENHOUSEGAS.sql
:r metadata/ValuePool/LANDUSE.sql
:r metadata/ValuePool/REGION.sql
