PRINT N'Creating Tables...';

:r tables/MetaAdm.sql
:r tables/MetabaseInfo.sql
:r tables/SpecialCharacter.sql
:r tables/SpecialCharacter_Sve.sql
:r tables/TimeScale.sql
:r tables/TimeScale_Sve.sql
:r tables/TextCatalog.sql
:r tables/TextCatalog_Sve.sql
:r tables/DataStorage.sql
:r tables/Organization.sql
:r tables/Organization_Sve.sql
:r tables/Person.sql
:r tables/MainTable.sql
:r tables/MenuSelection.sql
:r tables/MenuSelection_Sve.sql
:r tables/Link.sql
:r tables/Link_Sve.sql
:r tables/LinkMenuSelection.sql
:r tables/MainTable_Sve.sql
:r tables/SecondaryLanguage.sql
:r tables/MainTablePerson.sql
:r tables/ColumnCode.sql
:r tables/ColumnCode_Sve.sql
:r tables/Contents.sql
:r tables/ContentsTime.sql
:r tables/Contents_Sve.sql
:r tables/SubTable.sql
:r tables/SubTable_Sve.sql
:r tables/Variable.sql
:r tables/Variable_Sve.sql
:r tables/ValuePool.sql
:r tables/ValuePool_Sve.sql
:r tables/ValueSet.sql
:r tables/ValueSet_Sve.sql
:r tables/Value.sql
:r tables/Value_Sve.sql
:r tables/VSValue.sql
:r tables/VSValue_Sve.sql
:r tables/Grouping.sql
:r tables/Grouping_Sve.sql
:r tables/GroupingLevel.sql
:r tables/GroupingLevel_Sve.sql
:r tables/ValueGroup.sql
:r tables/ValueGroup_Sve.sql
:r tables/ValueSetGrouping.sql
:r tables/SubTableVariable.sql
:r tables/Attribute.sql
:r tables/Attribute_Sve.sql
:r tables/MainTableVariableHierarchy.sql
:r tables/Footnote.sql
:r tables/Footnote_Sve.sql
:r tables/FootnoteContents.sql
:r tables/FootnoteContTime.sql
:r tables/FootnoteContValue.sql
:r tables/FootnoteContVbl.sql
:r tables/FootnoteGrouping.sql
:r tables/FootnoteMainTable.sql
:r tables/FootnoteMaintTime.sql
:r tables/FootnoteMaintValue.sql
:r tables/FootnoteMenuSel.sql
:r tables/FootnoteSubTable.sql
:r tables/FootnoteValue.sql
:r tables/FootnoteValueSetValue.sql
:r tables/FootnoteVariable.sql

