INSERT INTO [dbo].[ValueSet]([ValueSet],[PresText],[Description],[Elimination],[ValuePool],[ValuePres],[GeoAreaNo],[MetaId],[SortCodeExists],[Footnote],[UserId],[LogDate]) VALUES(N'SUBJECTAREA', N'Subject area', N'Subject areas for official statistics', N'A', N'SUBJECTAREA', N'V', null, null, N'N', N'N', N'script', GETDATE());
INSERT INTO [dbo].[ValueSet_Sve]([ValueSet],[PresText],[Description],[UserId],[LogDate]) VALUES(N'SUBJECTAREA', N'Ämnesområden', N'Ämnesområden', N'script',GETDATE());

INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'AM',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'BE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'BO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'ME',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'EN',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'FM',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HA',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HS',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'JO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'KU',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'LE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'MI',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'NR',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'NV',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'OE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'PR',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'SO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'TK',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'UF',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'AA',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'OV',null,N'script',GETDATE());


INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'AM',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'BE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'BO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'ME',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'EN',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'FM',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HA',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'HS',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'JO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'KU',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'LE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'MI',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'NR',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'NV',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'OE',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'PR',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'SO',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'TK',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'UF',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'AA',null,N'script',GETDATE());
INSERT INTO [dbo].[VSValue_Sve]([ValueSet],[ValuePool],[ValueCode],[SortCode],[UserId],[LogDate]) VALUES(N'SUBJECTAREA','SUBJECTAREA',N'OV',null,N'script',GETDATE());
